networks:
  my_network:
   driver: bridge
services:
  api_project:
    build:
     context: .
     dockerfile: ./HotelReservationSystem.Api/Dockerfile
    container_name: api_project_container
    ports:
     - "5001:8080"
     - "5002:8081"
    environment:
     - ConnectionStrings__DefaultConnection=Server=db;Database=HotelReservationSystem;User Id=sa;Password=Sofan@12345#;Trusted_Connection=false;TrustServerCertificate=True;
    networks:
     - my_network
    depends_on:
     - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_container
    environment:
     SA_PASSWORD: "Sofan@12345#"
     ACCEPT_EULA: "Y"
    networks:
     - my_network
    ports:
     - "1433:1433"